### ISSUE TITLE
error conectin the ws service, ssl cert?

### ISSUE THREAD

**Issue by mckaygerhard** [antirek/owo-phone.js#5]
in the console js shows: hat browser cannot establish a connection in server at wss://10.101.10.197:8089/ws. sip.js:827

i made the documentation to starting guide, but only work the firts time (when i make it) later i try to reproduce it and cannot make works again any more..

any help are appreciable

**Comment by antirek** [comment]
why you use self-signed cert instead letsencrypt?

**Comment by mckaygerhard** [comment]
due in internal intranet there's no network connection, i mean, the example must work in any case, it suppost will work at my home in a intranet environment without network connection with outside world for dudies

**Comment by mckaygerhard** [comment]
now i have the "registered" message at the main screen, i discovered the sip behaviour changes beetween asterisk since version 12 to version 15, now sip was deprecated and a new module pjsip are implemented in version 15 as https://wiki.asterisk.org/wiki/display/AST/New+in+15 page wiki pointed.. that are why many of the tutorials does not work,, due are based on asterisk 11 or asterisk 15 that are not same for versions 13 and 14..

this error was fixed with commit 0a2d827b4ebeae87cc55e88846ddbc78daff672b with the required changes and fixes to implement asterisk with sipjs+owo-phone.js 

so now i have the "registered" message when push "save" button, but now, when try to make the call to demo number does not hear the answer.. well, the button changed to red and does not end the call or i dont know what must be happened at this point,  well one step ahead for now
